### ISSUE TITLE
关于训练经常中断的问题

### ISSUE THREAD

**Issue by anxiaonuoxyz** [starry-sky6688/StarCraft#60]
您好！我在选择qmix方法运行您的代码时经常会出现如下报错

XIO:  fatal IO error 25 (Inappropriate ioctl for device) on X server "localhost:16.0"
      after 2232 requests (2232 known processed) with 13 events remaining.
CloseHandler: 127.0.0.1:45238 disconnected

想请问一下您是否有遇到过以及如何解决的呢？如果可以解决的话十分感谢！

**Comment by starry-sky6688** [comment]
一般这种问题是机器网络的原因，你可以参考一下问题

https://github.com/starry-sky6688/StarCraft/issues/10

**Comment by anxiaonuoxyz** [comment]
> 一般这种问题是机器网络的原因，你可以参考一下问题 #10
谢谢您的解答，我还想向您详细描述一下，我同时跑了六张图来测试代码效果，其中五张图的程序报错如上，还有一张的报错如下

Error signal: '11'
Backtrace:
Traceback (most recent call last):
  File "/home/user-xc/miniconda3/envs/qmix/lib/python3.7/site-packages/websocket/_socket.py", line 115, in recv
    bytes_ = _recv()
  File "/home/user-xc/miniconda3/envs/qmix/lib/python3.7/site-packages/websocket/_socket.py", line 92, in _recv
    return sock.recv(bufsize)
socket.timeout: timed out
…………………………太长了 大概就是一堆time out
  File "/home/user-xc/miniconda3/envs/qmix/lib/python3.7/site-packages/pysc2/lib/protocol.py", line 153, in send
    raise ConnectionError("Error during %s: %s" % (name, e))
pysc2.lib.protocol.ConnectionError: Error during join_game: Websocket timed out.

看起来是socket通信问题，想请问一下是否可能是因为同时访问sc的接口导致冲突
